alter table CUBA_REQUEST_ITEM add constraint FK_CUBA_REQUEST_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references PRODUCT(ID);
alter table CUBA_REQUEST_ITEM add constraint FK_CUBA_REQUEST_ITEM_ON_REQUEST foreign key (REQUEST_ID) references CUBA_REQUEST(ID);
create index IDX_CUBA_REQUEST_ITEM_ON_PRODUCT on CUBA_REQUEST_ITEM (PRODUCT_ID);
create index IDX_CUBA_REQUEST_ITEM_ON_REQUEST on CUBA_REQUEST_ITEM (REQUEST_ID);
