-- begin SUPPLIER
create unique index IDX_SUPPLIER_UK_NAME on SUPPLIER (NAME)^
-- end SUPPLIER
-- begin CUSTOMER
create index IDX_CUBA_CUSTOMER_NAME on CUSTOMER (NAME)^
-- end CUSTOMER

-- begin PRODUCT
create index IDX_CUBA_PRODUCT_NAME on PRODUCT (NAME)^
-- end PRODUCT
-- begin CUBA_REQUEST_ITEM
alter table CUBA_REQUEST_ITEM add constraint FK_CUBA_REQUEST_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references PRODUCT(ID)^
alter table CUBA_REQUEST_ITEM add constraint FK_CUBA_REQUEST_ITEM_ON_REQUEST foreign key (REQUEST_ID) references CUBA_REQUEST(ID)^
create index IDX_CUBA_REQUEST_ITEM_ON_PRODUCT on CUBA_REQUEST_ITEM (PRODUCT_ID)^
create index IDX_CUBA_REQUEST_ITEM_ON_REQUEST on CUBA_REQUEST_ITEM (REQUEST_ID)^
-- end CUBA_REQUEST_ITEM
-- begin CUBA_REQUEST
alter table CUBA_REQUEST add constraint FK_CUBA_REQUEST_ON_CUSTOMER foreign key (CUSTOMER_ID) references CUSTOMER(ID)^
alter table CUBA_REQUEST add constraint FK_CUBA_REQUEST_ON_SUPPLIER foreign key (SUPPLIER_ID) references SUPPLIER(ID)^
create index IDX_CUBA_REQUEST_ON_CUSTOMER on CUBA_REQUEST (CUSTOMER_ID)^
create index IDX_CUBA_REQUEST_ON_SUPPLIER on CUBA_REQUEST (SUPPLIER_ID)^
-- end CUBA_REQUEST
